### ISSUE TITLE
Feature idea: close message with a click on the message

### ISSUE THREAD

**Issue by ronny332** [marcorinck/angular-growl#14]
This is just a short CSS modification to close the message with a click anywhere within the bubble.

``` CSS
.growl .growl-item {
  position: relative;
}

.growl .growl-item button {
  line-height: 0;
  font-size: 0;
  color: transparent;
  right: 0;
  top: 0;
  position: absolute;
  width: 100%;
  height: 100%;
}
```

With these styles added to your stylesheet the usage is more similar to the original growl behavior.

As next feature an interruption of the timeout delay would be very nice to keep the message on the screen (again more similar to the default growl settings at mac os).
This should be very easy to do by editing the source, but I will search for a shorter way from now on ;-).
